set -g status-bg red
set -g status-fg black
set-option -g status-style dim

unbind C-b
unbind '"'
unbind %
# nicer prefix
set -g prefix C-space
bind Space send-prefix
# splitting like spacemacs
bind | split-window -h
bind - split-window -v
bind _ split-window -v

# move panes without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
bind r source-file ~/.tmux.conf
set-window-option -g window-status-current-bg black

# Sane mouse scrolling
# Mouse usable to highlight text in copy mode
# set-option -g mouse on
# set -g mouse-utf8 on
# Sane mouse scrolling
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

setw -g automatic-rename
set-option -g default-terminal "screen-256color"
set-window-option -g mode-keys vi

